package com.yamal.feature.anime.api.model

data class AnimeForDetailsYamal(
    val id: Int,
    val title: String,
    val mainPicture: PictureYamal?,
    val alternativeTitles: AlternativeTitlesYamal?,
    val startDate: String?,
    val endDate: String?,
    val synopsis: String?,
    val mean: Float?,
    val rank: Int?,
    val popularity: Int?,
    val numListUsers: Int,
    val numScoringUsers: Int,
    val nsfw: String?,
    val genres: List<GenreYamal>,
    val createdAt: String,
    val updatedAt: String,
    val mediaType: MediaTypeYamal,
    val status: String,
    val myListStatus: AnimeListStatusYamal?,
    val numEpisodes: Int,
    val startSeason: AnimeSeasonYamal?,
    val broadcast: BroadcastYamal?,
    val source: String?,
    val averageEpisodeDuration: Int?,
    val rating: String?,
    val studios: List<AnimeStudioYamal>,
    val pictures: List<PictureYamal>,
    val background: String?,
    val relatedAnime: List<RelatedItemYamal<AnimeForListYamal>>,
    val relatedManga: List<RelatedItemYamal<MangaForListYamal>>,
    val recommendations: List<AnimeRecommendationYamal>,
    val statistics: AnimeStatisticsYamal?,
    // Jikan API additional fields
    val trailer: TrailerYamal? = null,
    val themeSongs: ThemeSongsYamal? = null,
    val streamingLinks: List<ExternalLinkYamal> = emptyList(),
    val externalLinks: List<ExternalLinkYamal> = emptyList(),
    val characters: List<AnimeCharacterYamal> = emptyList(),
    val reviews: List<AnimeReviewYamal> = emptyList(),
)
